### ISSUE TITLE
panic when start record on egress:v1.5.6

### ISSUE THREAD

**Issue by ocean2811** [livekit/egress#272]
log print:

2023-02-28T10:05:35.648120520Z panic: interface conversion: protoreflect.ProtoMessage is *livekit.StartEgressRequest, not *rpc.StartEgressRequest
2023-02-28T10:05:35.648189761Z
2023-02-28T10:05:35.648196241Z goroutine 69 [running]:
2023-02-28T10:05:35.648200714Z github.com/livekit/psrpc.(*rpcHandlerImpl[...]).handleRequest(0xc000439e60, 0xc000427860, 0xc0003000e0?)
2023-02-28T10:05:35.648205074Z  /root/go/pkg/mod/github.com/livekit/psrpc@v0.2.7/server_handler.go:139 +0x396
2023-02-28T10:05:35.648209049Z github.com/livekit/psrpc.(*rpcHandlerImpl[...]).run.func1.1()
2023-02-28T10:05:35.648212898Z  /root/go/pkg/mod/github.com/livekit/psrpc@v0.2.7/server_handler.go:103 +0x36
2023-02-28T10:05:35.648216554Z created by github.com/livekit/psrpc.(*rpcHandlerImpl[...]).run.func1
2023-02-28T10:05:35.648231693Z  /root/go/pkg/mod/github.com/livekit/psrpc@v0.2.7/server_handler.go:102 +0x30e

**Comment by frostbyte73** [comment]
If you have psrpc is enabled in the config, please upgrade to livekit-server v1.3.5
