### ISSUE TITLE
Runtime Error: Invalid Memory Address. After Upgrade to 1.6.0

### ISSUE THREAD

**Issue by ozgur-d** [livekit/egress#291]
### My environment

Egress and livekit server are installed on two different servers in the same local network. The redis server is installed on the same server like the livekit server. Egress communicates with redis and livekit over the local network, not public. for example: ws://10.0.0.4:7880

### Issue

I updated my egress docker image from version 1.5.5 to version 1.6.0.  I call startRoomCompositeEgress function to start stream and I get successful response. But after a while egress gives an error and the stream is stopped. And my livekit server logs contains my servers public ip addresses but i didn't communicate via public ip adress. I shared it with you as LIVEKIT_SERVER_PUBLIC_IP and EGRESS_SERVER_PUBLIC_IP in the livekit logs.

I could not find the cause of the problem. When I revert back to version 1.5.5 it works correctly.

StartRoomCompositeEgress typescript:

```
const encodingOptions: EncodingOptions = {
        width: 1920,
        height: 1080,
        framerate: 30,
        videoBitrate: 9000,
        videoCodec: VideoCodec.H264_MAIN,
        audioBitrate: 128,
        audioCodec: AudioCodec.AAC,
        depth: 24,
        audioFrequency: 44100,
      };

      const options: RoomCompositeOptions = {
        layout: roomSettings.streamLayout,
        encodingOptions: encodingOptions,
      };
      
const rtmpOutput: StreamOutput = {
        protocol: StreamProtocol.RTMP,
        urls: roomSettings.streamUrls.map((url) => url.url),
      };

      const streamInfo = await this.egressClient.startRoomCompositeEgress(
        roomMember.room.uid,
        rtmpOutput,
        options,
      );
```

Egress Log

```
2023-03-13T11:53:00.020Z        DEBUG   egress  service/handler_deprecated.go:108       handling request        {"nodeID": "NE_VypyLcqobuTd", "handlerID": "EGH_bkHiTb4T42sJ", "clusterID": "", "egressID": "EG_aT2Jmgw7nVbY", "egressID": "EG_aT2Jmgw7nVbY", "requestID": "RPC_aaciiAcWw4VF"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x14735e5]

goroutine 1 [running]:
github.com/livekit/egress/pkg/pipeline.(*Pipeline).removeSink(0xc000627480, {0xc00061a960, 0x57}, {0x0, 0x0})
        /workspace/pkg/pipeline/pipeline.go:282 +0x145
github.com/livekit/egress/pkg/pipeline.(*Pipeline).UpdateStream(0xc000627480, {0x1d75810?, 0xc000040028?}, 0xc0002ae690)
        /workspace/pkg/pipeline/pipeline.go:263 +0x24d
github.com/livekit/egress/pkg/service.(*HandlerV0).Run(0xc0005df4d0)
        /workspace/pkg/service/handler_deprecated.go:112 +0x7c5
main.runHandler(0xc00028a580?)
        /workspace/cmd/server/main.go:215 +0x3dd
github.com/urfave/cli/v2.(*Command).Run(0xc00028a580, 0xc0001f7480, {0xc0003dc000, 0x7, 0x7})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0xa42
github.com/urfave/cli/v2.(*Command).Run(0xc00028a840, 0xc0001f72c0, {0xc00003c180, 0x8, 0x8})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc8a
github.com/urfave/cli/v2.(*App).RunContext(0xc00047b0e0, {0x1d75810?, 0xc000040028}, {0xc00003c180, 0x8, 0x8})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x605
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
        /workspace/cmd/server/main.go:71 +0x47c
2023-03-13T11:53:00.029Z        ERROR   egress  service/manager.go:132  process failed  {"nodeID": "NE_VypyLcqobuTd", "clusterID": "", "error": "exit status 2"}
github.com/livekit/egress/pkg/service.(*ProcessManager).awaitCleanup
        /workspace/pkg/service/manager.go:132
2023-03-13T11:53:00.030Z        WARN    egress  service/handler.go:202  egress failed   {"nodeID": "NE_VypyLcqobuTd", "clusterID": "", "egressID": "EG_aT2Jmgw7nVbY", "request_type": "room_composite", "output_type": "stream", "error": "exit status 2"}
2023-03-13T11:53:00.032Z        INFO    egress  service/service_deprecated.go:33        shutting down   {"nodeID": "NE_VypyLcqobuTd", "clusterID": ""}
```
Livekit server logs
```
0|livekit-server    | 2023-03-13T11:52:56: 2023-03-13T11:52:56.273Z     INFO    livekit service/egress.go:189   using deprecated egress client
0|livekit-server    | 2023-03-13T11:52:56: 2023-03-13T11:52:56.276Z     INFO    livekit service/twirp.go:128    API Egress.StartRoomCompositeEgress     {"service": "Egress", "method": "StartRoomCompositeEgress", "room": "2083548a-3a91-496b-af78-b2454bb312b0", "baseUrl": "", "outputType": "*livekit.RoomCompositeEgressRequest_Stream", "egressID": "EG_aT2Jmgw7nVbY", "duration": "3.850166ms", "status": "200"}
0|livekit-server    | 2023-03-13T11:52:57: 2023-03-13T11:52:57.271Z     INFO    livekit rtc/room.go:327 new participant joined  {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "pID": "PA_GgcRkb8xAZoT", "participant": "EG_aT2Jmgw7nVbY", "protocol": 8, "options": {"AutoSubscribe":true}}
0|livekit-server    | 2023-03-13T11:52:57: 2023-03-13T11:52:57.272Z     INFO    livekit rtc/room.go:263 participant state changed       {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "state": "JOINED", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "oldState": "JOINING"}
0|livekit-server    | 2023-03-13T11:52:57: 2023-03-13T11:52:57.272Z     INFO    livekit rtc/participant.go:1105 sending offer   {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "remote": false, "transport": "SUBSCRIBER"}
0|livekit-server    | 2023-03-13T11:52:57: 2023-03-13T11:52:57.274Z     INFO    livekit service/rtcservice.go:258       new client WS connected {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "remote": false, "connID": "CO_FREEYkrHWgRm"}
0|livekit-server    | 2023-03-13T11:52:57: 2023-03-13T11:52:57.290Z     INFO    livekit rtc/participant.go:490  received answer {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "remote": false, "transport": "SUBSCRIBER"}
0|livekit-server    | 2023-03-13T11:52:58: 2023-03-13T11:52:58.297Z     INFO    livekit rtc/transport.go:599    selected ICE candidate pair     {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host LIVEKIT_SERVER_PUBLIC_IP:53126 <-> (remote) udp4 prflx EGRESS_SERVER_PUBLIC_IP:37456 related :0"}
0|livekit-server    | 2023-03-13T11:52:58: 2023-03-13T11:52:58.306Z     INFO    livekit rtc/room.go:263 participant state changed       {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "state": "ACTIVE", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "oldState": "JOINED"}
0|livekit-server    | 2023-03-13T11:53:00: 2023-03-13T11:53:00.007Z     INFO    livekit service/twirp.go:128    API Egress.ListEgress   {"service": "Egress", "method": "ListEgress", "duration": "1.341723ms", "status": "200"}
0|livekit-server    | 2023-03-13T11:53:00: 2023-03-13T11:53:00.011Z     INFO    livekit service/twirp.go:128    API Egress.ListEgress   {"service": "Egress", "method": "ListEgress", "duration": "5.043286ms", "status": "200"}
0|livekit-server    | 2023-03-13T11:53:00: 2023-03-13T11:53:00.017Z     INFO    livekit service/twirp.go:128    API RoomService.ListParticipants        {"service": "RoomService", "method": "ListParticipants", "room": "2083548a-3a91-496b-af78-b2454bb312b0", "duration": "363.806µs", "status": "200"}
0|livekit-server    | 2023-03-13T11:53:00: 2023-03-13T11:53:00.031Z     INFO    livekit service/rtcservice.go:231       finishing WS connection {"room": "2083548a-3a91-496b-af78-b2454bb312b0", "roomID": "RM_aQGx8LQCyaSr", "participant": "EG_aT2Jmgw7nVbY", "pID": "PA_GgcRkb8xAZoT", "remote": false, "connID": "CO_FREEYkrHWgRm"}
0|livekit-server    | 2023-03-13T11:53:00: 2023-03-13T11:53:00.031Z     ERROR   livekit service/ioinfo.go:89    egress failed   {"egressID": "EG_aT2Jmgw7nVbY", "error": "exit status 2"}
```

**Comment by frostbyte73** [comment]
Hey @ozgur-d, it looks like the panic was caused by the `UpdateStream` RPC being called with a url that wasn't part of the pipeline.
I've fixed the panic in https://github.com/livekit/egress/pull/301.

As a side note, it's recommended to add 
```
egress:
  use_psrpc: true
```
 to your livekit config to upgrade the internal communication system (https://github.com/livekit/livekit/blob/master/pkg/config/config.go#L253)
