### ISSUE TITLE
[BUG] Fail to connect livekit with meet demo after egress request

### ISSUE THREAD

**Issue by calvin-seo** [livekit/egress#343]
**Describe the bug**
Unable to connect livekit with [Livekit Meet](https://meet.livekit.io/?tab=custom) whenever egress recording is requested. If I disable the recording, it works very well.

I posted the same issue (https://github.com/livekit/meet/issues/58) to livekit/meet repo because I am not sure which side causes the issue

**Egress Version**
v1.6.0

**Egress Request**
- RoomComposite Egress
- TrackComposite Egress

My application makes those two requests whenever it receives webhooks
- Room_Started Webhook triggers RoomComposite request
- Track_Published Webhook triggers TrackCompsite request

I am not sure this is a proper way to make egress requests tho

**Logs**
This is a console log of my web browser when I try to connect to my livekit
```
framework-7751730b10fa0f74.js:9 TypeError: Cannot read properties of undefined (reading 'matchAll')
    at 590-005945d272d18427.js:1:101542
    at Array.map (<anonymous>)
    at 590-005945d272d18427.js:1:101514
    at rx (590-005945d272d18427.js:1:101958)
    at 590-005945d272d18427.js:1:100800
    at Object.useMemo (framework-7751730b10fa0f74.js:9:67913)
    at n.useMemo (framework-7751730b10fa0f74.js:25:5985)
    at rE (590-005945d272d18427.js:1:100786)
    at aD (framework-7751730b10fa0f74.js:9:61583)
    at i (framework-7751730b10fa0f74.js:9:119731)

main-cca64c2bc7b52412.js:1 TypeError: Cannot read properties of undefined (reading 'matchAll')
    at 590-005945d272d18427.js:1:101542
    at Array.map (<anonymous>)
    at 590-005945d272d18427.js:1:101514
    at rx (590-005945d272d18427.js:1:101958)
    at 590-005945d272d18427.js:1:100800
    at Object.useMemo (framework-7751730b10fa0f74.js:9:67913)
    at n.useMemo (framework-7751730b10fa0f74.js:25:5985)
    at rE (590-005945d272d18427.js:1:100786)
    at aD (framework-7751730b10fa0f74.js:9:61583)
    at i (framework-7751730b10fa0f74.js:9:119731)
```

**Comment by lukasIO** [comment]
meet repo is the right place
