### ISSUE TITLE
Record error when I use Egress Custom template

### ISSUE THREAD

**Issue by toskeyfine** [livekit/egress#433]
**Describe the bug**
Record error when I use Egress Custom template

**Egress Version**
v1.7.2

**Egress Request**
Post the request here (be sure to remove any PII).

**Additional context**
use docker latest images .
livekit-server : v1.4.3

**Logs**
`2023-07-13T07:45:04.019Z        INFO    egress  service/service.go:111  request received        {"nodeID": "NE_4y3h8rfMFEg6", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU"}
2023-07-13T07:45:04.020Z        INFO    egress  service/service.go:119  request validated       {"nodeID": "NE_4y3h8rfMFEg6", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "request_type": "room_composite", "output_type": "segments", "room": "944561981", "request": {"RoomComposite":{"room_name":"944561981","layout":"grid","Output":{"Segments":{"protocol":1,"filename_prefix":"/out/944561981/e826b27c810e425bac32385001b15673/944561981_segment_","playlist_name":"944561981.m3u8","segment_duration":300,"Output":null}},"Options":null,"segment_outputs":[{"protocol":1,"filename_prefix":"/out/944561981/e826b27c810e425bac32385001b15673/944561981_segment_","playlist_name":"944561981.m3u8","segment_duration":300,"Output":null}]}}}
2023-07-13T07:45:04.063Z        DEBUG   egress  server/main.go:169      handler launched        {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU"}
2023-07-13T07:45:04.063Z        INFO    egress  redis/redis.go:92       connecting to redis     {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "simple": true, "addr": "10.67.78.29:6379"}
2023-07-13T07:45:04.080Z        DEBUG   egress  source/web.go:137       launching xvfb  {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "display": ":1084301935", "dims": "1920x1080x24"}
2023-07-13T07:45:04.083Z        DEBUG   egress  source/web.go:172       launching chrome        {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "url": "http://10.67.78.29:8086?layout=grid&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkzMjA3MDQsImlzcyI6InByb2RrZXkiLCJuYmYiOjE2ODkyMzQzMDQsInN1YiI6IkVHX0NXS3h6clo1a01wVSIsInZpZGVvIjp7ImNhblB1Ymxpc2giOmZhbHNlLCJjYW5QdWJsaXNoRGF0YSI6ZmFsc2UsImNhblN1YnNjcmliZSI6dHJ1ZSwiaGlkZGVuIjp0cnVlLCJyZWNvcmRlciI6dHJ1ZSwicm9vbSI6Ijk0NDU2MTk4MSIsInJvb21Kb2luIjp0cnVlfX0.P7OUCWxxOnUQj0A-92aqQU6r9RyHvKsIHHl5n1ecqwU&url=ws%3A%2F%2F10.67.78.29%3A7880"}
2023-07-13T07:45:20.049Z        INFO    egress  source/web.go:250       chrome: END_RECORDING   {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU"}
2023-07-13T07:45:20.053Z        DEBUG   egress  source/web.go:293       chrome exception        {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "timestamp": 1689234320052, "exceptionDetails": {"columnNumber":25648,"exception":{"className":"te","description":"Error: could not establish pc connection\n    at http://10.67.78.29:8086/assets/meet-room-participator-a0653053.js:37:25649","objectId":"-6653493728736986577.2.1","preview":{"description":"Error: could not establish pc connection\n    at http://10.67.78.29:8086/assets/meet-room-participator-a0653053.js:37:25649","overflow":false,"properties":[{"name":"code","type":"number","value":"1"},{"name":"status","type":"undefined","value":"undefined"},{"name":"reason","type":"undefined","value":"undefined"},{"name":"stack","type":"string","value":"Error: could not establish pc connection\n    at ht…ssets/meet-room-participator-a0653053.js:37:25649"},{"name":"message","type":"string","value":"could not establish pc connection"}],"subtype":"error","type":"object"},"subtype":"error","type":"object"},"exceptionId":1,"executionContextId":2,"lineNumber":36,"scriptId":"8","stackTrace":{"callFrames":[{"columnNumber":25648,"functionName":"","lineNumber":36,"scriptId":"8","url":"http://10.67.78.29:8086/assets/meet-room-participator-a0653053.js"}]},"text":"Uncaught (in promise)","url":"http://10.67.78.29:8086/assets/meet-room-participator-a0653053.js"}}
2023-07-13T07:45:23.266Z        INFO    egress  service/handler.go:202  egress updated  {"nodeID": "NE_4y3h8rfMFEg6", "handlerID": "EGH_eesHNTHXMjD3", "clusterID": "", "egressID": "EG_CWKxzrZ5kMpU", "egressID": "EG_CWKxzrZ5kMpU", "request_type": "room_composite", "output_type": "segments", "status": "EGRESS_ABORTED"}`

**Comment by davidzhao** [comment]
are you self-hosting? it's possible this is a security restriction because your template isn't hosted on `https`

**Comment by toskeyfine** [comment]
Another problem is that EGRESS records are empty when there are attendees in the room but no activity track

**Comment by davidzhao** [comment]
sorry, I'm not sure how to help with self-signed certificates.
